### ISSUE TITLE
[BUG]: Keras and SavedModel conversion always leads to "something went wrong while converting"

### ISSUE THREAD

**Issue by JeremySOfficial** [googlecreativelab/teachablemachine-community#217] opened 2021-06-10 17:18 UTC
After clicking the exporting the model, went into the tensorflow tab, and select either keras or SavedModel type of conversion and "download my model" will always download model but error mention "Something went wrong while converting". Also, the zip file cannot be extracted and the file is in error

 - Windows 10 Home 21H1
 - Web Browser: Chrome (Version: Version 91.0.4472.77 (Official Build) (64-bit))

![Error](https://user-images.githubusercontent.com/54141114/121568934-d2efec00-ca52-11eb-866c-f20851d70170.JPG)

**Comment by HalfdanJ** [comment] 2021-08-09 21:20
Duplicate of #225 that is now hopefully resolved.

**Closed by HalfdanJ** 2021-08-09 21:20 UTC
Labels: bug
