### ISSUE TITLE
Upload samples Audio created outside TM

### ISSUE THREAD

**Issue by djovanoski** [googlecreativelab/teachablemachine-community#106] opened 2020-04-27 07:51 UTC
Hello, 

I want to ask if it is possible to create samples outside TM and upload them for example for Audio Project?

**Comment by irealva** [comment] 2020-05-20 19:16
Not at the moment sorry!

**Comment by irealva** [comment] 2020-05-20 19:22
Closing but making a note about your request for the audio upload. Thanks!

**Comment by irealva** [comment] 2020-05-20 19:47
Duplicate of #77 .

**Closed** 2020-05-20 19:47 UTC
Labels: enhancement
