### ISSUE TITLE
.tflite support for PoseEstimation

### ISSUE THREAD

**Issue by ankitsinghal04** [googlecreativelab/teachablemachine-community#104] opened 2020-04-16 22:18 UTC
I realize this issue was sort of brought up in issue #36, I was just wondering if there was any update as to when this feature might be available (downloading .tflite models for the pose estimation)? Same thing for the audio classification?

I was building an app and just wanted to know if this was coming out soon or not.

**Comment by irealva** [comment] 2020-05-20 19:49
Hi, no update yet on the pose or audio front. It's a highly requested feature and we definitely have it in our feature list.

**Comment by irealva** [comment] 2020-10-29 21:26
Duplicate of [#117](https://github.com/googlecreativelab/teachablemachine-community/issues/117)

**Comment by irealva** [comment] 2020-10-29 21:26
Thanks for your feature request idea. We're going to close this issue for now as we're not actively working on it just yet, but rest assured we've made a note of it.

**Closed by irealva** 2020-10-29 21:26 UTC
Labels: feature request
